sudo: required
language: java
jdk:
    - oraclejdk8
install:
    - wget https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar
script:
    - java -jar BuildTools.jar
    - mvn package
notifications:
    email: false
