teleports:
    default:
        enabled: true
        cooldown: 5
        cost: 15
        cooldown-multiplier: .5
        cost-multiplier: .5
    home:
        enabled: true
        cooldown: 5
        cost: 15
        cooldown-multiplier: .5
        cost-multiplier: .5
    spawn:
        enabled: true
        cooldown: 5
        cost: 10
        cooldown-multiplier: .5
        cost-multiplier: .5
    tp:
        enabled: true
        cooldown: 10
        cost: 25
        cooldown-multiplier: .5
        cost-multiplier: .5
    tpa:
        enabled: true
        cooldown: 10
        cost: 25
        cooldown-multiplier: .5
        cost-multiplier: .5
    backward:
        enabled: true
        cooldown: 60
        cost: 50
        cooldown-multiplier: .5
        cost-multiplier: .5
    forward:
        enabled: true
        cooldown: 60
        cost: 50
        cooldown-multiplier: .5
        cost-multiplier: .5

override:
    cooldown:
        op: true
    cost:
        op: true

periodic:
    frequency: 180
    cooldown-multiplier-decrease: .5
    cost-multiplier-decrease: .5

tpa:
    requestDuration: 15

economy:
    enabled: false

debug: false