teleports:
    home:
        enabled: true
        cooldown: 5
        cost: 10
        cooldown-multiplier: .5
        cost-multiplier: .5
    spawn:
        enabled: true
        cooldown: 5
        cost: 10
        cooldown-multiplier: .5
        cost-multiplier: .5
    tp:
        enabled: true
        cooldown: 10
        cost: 10
        cooldown-multiplier: .5
        cost-multiplier: .5
    tpa:
        enabled: true
        cooldown: 10
        cost: 10
        cooldown-multiplier: .5
        cost-multiplier: .5

periodic:
    frequency: 20
    cooldown-multiplier-decrease: .5
    cost-multiplier-decrease: .5

economy:
    enabled: false

debug: false