name: ${project.name}
version: ${project.version}
description: ${project.description}
author: Jerred Shepherd (RiotShielder)
website: http://shepherdjerred.com/

main: com.shepherdjerred.stteleports.Main

commands:
    stteleports:
        description: Handles plugin related functions
        aliases: [sttp]
    teleport:
        description: Teleport command
        aliases: [tp]
    tpa:
        description: Teleport request command
        aliases: [tpr]
    home:
        description: Home command
        aliases: []
    sethome:
        description: Sethome command
        aliases: []

permissions:
    stTeleports.*:
        description: Gives access to all plugin functions
        children:
            stSkills.admin.*: true
    stTeleports.admin.*:
        description: Gives access to all admin commands
        children:
          stSkills.admin.reload: true
    stTeleports.admin.reload:
        description: Gives access to /sttp reload
        default: OP